[build-system]
requires = [ "setuptools" ]
build-backend = "setuptools.build_meta"

[project]
name = "vulnerabilities"
version = "0.1"
dependencies = [
    "bottle"
]

[tool.setuptools.packages.find]
include = ["app*", "core*", "interfaces*", "mock*", "tree_parser*"]
exclude = ["data*", "result*", "tests*"]

[project.scripts]
vuln-scanner = "app.app:main"
vuln-web = "app.app:run_scan"
