[build-system]
requires = [ "setuptools" ]
build-backend = "setuptools.build_meta"

[project]
name = "storage"
version = "0.1"
dependencies = [
    "bottle",
]

[tool.setuptools.packages.find]
include = ["app*"]
exclude = ["docs*", "tests*"]

[project.scripts]
storage-web = "app.web:main"
storage-scanner = "app.scanner:main"
