[build-system]
requires = [ "setuptools" ]
build-backend = "setuptools.build_meta"

[project]
name = "read_waveplus"
version = "0.1"
dependencies = [
    "bluepy",
    "pandas"
]

[project.scripts]
read_waveplus = "app:main"
